chore(format): migrate biome formatter to oxfmt

diff --git a/apps/discourse/templates/web.template.yml b/apps/discourse/templates/web.template.yml
--- a/apps/discourse/templates/web.template.yml
+++ b/apps/discourse/templates/web.template.yml
@@ -30,16 +30,16 @@ run:
   # TODO: move to base image (anacron can not be fired up using rc.d)
   - exec: rm -f /etc/cron.d/anacron
   - file:
-     path: /etc/cron.d/anacron
-     contents: |
+      path: /etc/cron.d/anacron
+      contents: |
         SHELL=/bin/sh
         PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 
         30 7    * * *   root	/usr/sbin/anacron -s >/dev/null
   - file:
-     path: /etc/runit/1.d/copy-env
-     chmod: "+x"
-     contents: |
+      path: /etc/runit/1.d/copy-env
+      chmod: '+x'
+      contents: |
         #!/bin/bash
         env > ~/boot_env
         conf=/var/www/discourse/config/discourse.conf
@@ -48,9 +48,9 @@ run:
         /usr/local/bin/ruby -e 'ENV.each{|k,v| puts "#{$1.downcase} = '\''#{v}'\''" if k =~ /^DISCOURSE_(.*)/}' | install -m 600 -o discourse /dev/stdin ${conf}
 
   - file:
-     path: /etc/service/unicorn/run
-     chmod: "+x"
-     contents: |
+      path: /etc/service/unicorn/run
+      chmod: '+x'
+      contents: |
         #!/bin/bash
         exec 2>&1
         # redis
@@ -73,26 +73,26 @@ run:
         LD_PRELOAD=$RUBY_ALLOCATOR HOME=/home/discourse USER=discourse exec thpoff chpst -u discourse:www-data -U discourse:www-data bundle exec config/unicorn_launcher -E production -c config/unicorn.conf.rb
 
   - file:
-     path: /etc/service/nginx/run
-     chmod: "+x"
-     contents: |
+      path: /etc/service/nginx/run
+      chmod: '+x'
+      contents: |
         #!/bin/sh
         exec 2>&1
         exec /usr/sbin/nginx
 
   - file:
-     path: /etc/runit/3.d/01-nginx
-     chmod: "+x"
-     contents: |
-       #!/bin/bash
-       sv stop nginx
+      path: /etc/runit/3.d/01-nginx
+      chmod: '+x'
+      contents: |
+        #!/bin/bash
+        sv stop nginx
 
   - file:
-     path: /etc/runit/3.d/02-unicorn
-     chmod: "+x"
-     contents: |
-       #!/bin/bash
-       sv stop unicorn
+      path: /etc/runit/3.d/02-unicorn
+      chmod: '+x'
+      contents: |
+        #!/bin/bash
+        sv stop unicorn
 
   - exec:
       cd: $home
@@ -124,30 +124,30 @@ run:
         - bash -c "ln    -s           /shared/tmp/{backups,restores} $home/tmp"
         - chown -R discourse:www-data /shared/log/rails /shared/uploads /shared/backups /shared/tmp
         # scrub broken symlinks from plugins that have been removed
-        - "[ ! -d public/plugins ] || find public/plugins/ -maxdepth 1 -xtype l -delete"
+        - '[ ! -d public/plugins ] || find public/plugins/ -maxdepth 1 -xtype l -delete'
 
   - exec:
       cmd:
-        - "cp $home/config/nginx.sample.conf /etc/nginx/conf.d/discourse.conf"
-        - "rm /etc/nginx/sites-enabled/default"
-        - "mkdir -p /var/nginx/cache"
+        - 'cp $home/config/nginx.sample.conf /etc/nginx/conf.d/discourse.conf'
+        - 'rm /etc/nginx/sites-enabled/default'
+        - 'mkdir -p /var/nginx/cache'
 
         # Stop building the container if the Nginx outlets are missing
-        - "grep -q 'outlets/before-server' /etc/nginx/conf.d/discourse.conf || ( >&2 echo 'The \"before-server\" Nginx outlet is missing. This version of discourse_docker is not compatible with the chosen Discourse version.' ; exit 1 )"
-        - "grep -q 'outlets/server' /etc/nginx/conf.d/discourse.conf || ( >&2 echo 'The \"server\" Nginx outlet is missing. This version of discourse_docker is not compatible with the chosen Discourse version.' ; exit 1 )"
-        - "grep -q 'outlets/discourse' /etc/nginx/conf.d/discourse.conf || ( >&2 echo 'The \"discourse\" Nginx outlet is missing. This version of discourse_docker is not compatible with the chosen Discourse version.' ; exit 1 )"
+        - 'grep -q ''outlets/before-server'' /etc/nginx/conf.d/discourse.conf || ( >&2 echo ''The "before-server" Nginx outlet is missing. This version of discourse_docker is not compatible with the chosen Discourse version.'' ; exit 1 )'
+        - 'grep -q ''outlets/server'' /etc/nginx/conf.d/discourse.conf || ( >&2 echo ''The "server" Nginx outlet is missing. This version of discourse_docker is not compatible with the chosen Discourse version.'' ; exit 1 )'
+        - 'grep -q ''outlets/discourse'' /etc/nginx/conf.d/discourse.conf || ( >&2 echo ''The "discourse" Nginx outlet is missing. This version of discourse_docker is not compatible with the chosen Discourse version.'' ; exit 1 )'
 
         # Create placeholders for the Nginx outlets
-        - "mkdir -p /etc/nginx/conf.d/outlets/before-server"
-        - "touch /etc/nginx/conf.d/outlets/before-server/20-redirect-http-to-https.conf"
-        - "touch /etc/nginx/conf.d/outlets/before-server/30-ratelimited.conf"
-        - "mkdir -p /etc/nginx/conf.d/outlets/server"
-        - "touch /etc/nginx/conf.d/outlets/server/10-http.conf"
-        - "touch /etc/nginx/conf.d/outlets/server/20-https.conf"
-        - "touch /etc/nginx/conf.d/outlets/server/30-offline-page.conf"
-        - "mkdir -p /etc/nginx/conf.d/outlets/discourse"
-        - "touch /etc/nginx/conf.d/outlets/discourse/20-https.conf"
-        - "touch /etc/nginx/conf.d/outlets/discourse/30-ratelimited.conf"
+        - 'mkdir -p /etc/nginx/conf.d/outlets/before-server'
+        - 'touch /etc/nginx/conf.d/outlets/before-server/20-redirect-http-to-https.conf'
+        - 'touch /etc/nginx/conf.d/outlets/before-server/30-ratelimited.conf'
+        - 'mkdir -p /etc/nginx/conf.d/outlets/server'
+        - 'touch /etc/nginx/conf.d/outlets/server/10-http.conf'
+        - 'touch /etc/nginx/conf.d/outlets/server/20-https.conf'
+        - 'touch /etc/nginx/conf.d/outlets/server/30-offline-page.conf'
+        - 'mkdir -p /etc/nginx/conf.d/outlets/discourse'
+        - 'touch /etc/nginx/conf.d/outlets/discourse/20-https.conf'
+        - 'touch /etc/nginx/conf.d/outlets/discourse/30-ratelimited.conf'
 
   - replace:
       filename: /etc/nginx/nginx.conf
@@ -155,12 +155,12 @@ run:
       to: daemon off;
 
   - replace:
-      filename: "/etc/nginx/nginx.conf"
+      filename: '/etc/nginx/nginx.conf'
       from: /worker_connections.+$/
       to: worker_connections $nginx_worker_connections;
 
   - replace:
-      filename: "/etc/nginx/conf.d/discourse.conf"
+      filename: '/etc/nginx/conf.d/discourse.conf'
       from: /client_max_body_size.+$/
       to: client_max_body_size $upload_size;
 
@@ -240,56 +240,56 @@ run:
   - replace:
       tag: precompile
       filename: /etc/service/unicorn/run
-      from: "# before precompile"
-      to: "PRECOMPILE_ON_BOOT=0"
+      from: '# before precompile'
+      to: 'PRECOMPILE_ON_BOOT=0'
 
   - file:
-     path: /usr/local/bin/discourse
-     chmod: +x
-     contents: |
-       #!/bin/bash
-       (cd /var/www/discourse && RAILS_ENV=production sudo -H -E -u discourse bundle exec script/discourse "$@")
+      path: /usr/local/bin/discourse
+      chmod: +x
+      contents: |
+        #!/bin/bash
+        (cd /var/www/discourse && RAILS_ENV=production sudo -H -E -u discourse bundle exec script/discourse "$@")
 
   - file:
-     path: /usr/local/bin/rails
-     chmod: +x
-     contents: |
-       #!/bin/bash
-       (cd /var/www/discourse && RAILS_ENV=production sudo -H -E -u discourse bundle exec script/rails "$@")
+      path: /usr/local/bin/rails
+      chmod: +x
+      contents: |
+        #!/bin/bash
+        (cd /var/www/discourse && RAILS_ENV=production sudo -H -E -u discourse bundle exec script/rails "$@")
 
   - file:
-     path: /usr/local/bin/rake
-     chmod: +x
-     contents: |
-       #!/bin/bash
-       (cd /var/www/discourse && RAILS_ENV=production sudo -H -E -u discourse bundle exec bin/rake "$@")
+      path: /usr/local/bin/rake
+      chmod: +x
+      contents: |
+        #!/bin/bash
+        (cd /var/www/discourse && RAILS_ENV=production sudo -H -E -u discourse bundle exec bin/rake "$@")
 
   - file:
-     path: /usr/local/bin/rbtrace
-     chmod: +x
-     contents: |
-       #!/bin/bash
-       (cd /var/www/discourse && RAILS_ENV=production sudo -H -E -u discourse bundle exec rbtrace "$@")
+      path: /usr/local/bin/rbtrace
+      chmod: +x
+      contents: |
+        #!/bin/bash
+        (cd /var/www/discourse && RAILS_ENV=production sudo -H -E -u discourse bundle exec rbtrace "$@")
 
   - file:
-     path: /usr/local/bin/stackprof
-     chmod: +x
-     contents: |
-       #!/bin/bash
-       (cd /var/www/discourse && RAILS_ENV=production sudo -H -E -u discourse bundle exec stackprof "$@")
+      path: /usr/local/bin/stackprof
+      chmod: +x
+      contents: |
+        #!/bin/bash
+        (cd /var/www/discourse && RAILS_ENV=production sudo -H -E -u discourse bundle exec stackprof "$@")
 
   - file:
-     path: /etc/update-motd.d/10-web
-     chmod: +x
-     contents: |
-       #!/bin/bash
-       echo
-       echo Use: rails, rake or discourse to execute commands in production
-       echo
+      path: /etc/update-motd.d/10-web
+      chmod: +x
+      contents: |
+        #!/bin/bash
+        echo
+        echo Use: rails, rake or discourse to execute commands in production
+        echo
 
   - file:
-     path: /etc/logrotate.d/rails
-     contents: |
+      path: /etc/logrotate.d/rails
+      contents: |
         /shared/log/rails/*.log
         {
                 rotate 7
@@ -303,8 +303,8 @@ run:
         }
 
   - file:
-     path: /etc/logrotate.d/nginx
-     contents: |
+      path: /etc/logrotate.d/nginx
+      contents: |
         /var/log/nginx/*.log {
           daily
           missingok
@@ -362,14 +362,14 @@ run:
         /bin/rm -f /var/www/discourse/tmp/pids/*.pid
   # change login directory to Discourse home
   - file:
-     path: /root/.bash_profile
-     chmod: 644
-     contents: |
+      path: /root/.bash_profile
+      chmod: 644
+      contents: |
         cd $home
 
   - file:
-     path: /usr/local/etc/ImageMagick-7/policy.xml
-     contents: |
+      path: /usr/local/etc/ImageMagick-7/policy.xml
+      contents: |
         <?xml version="1.0" encoding="UTF-8"?>
         <!DOCTYPE policymap [
           <!ELEMENT policymap (policy)+>
